name: Generate Allure Report

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:   # позволяет запускать вручную

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.3.0

      - name: Set up JDK 11
        uses: actions/setup-java@v4.10.0
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4.3.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with Maven
        run: mvn clean test

      - name: Generate Allure report
        run: mvn allure:report

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
          destination_dir: ./allure-report
          keep_files: false
